- id: Atrium Lights On
  alias: Atrium Lights On
  trigger:
  - entity_id: sensor.front_door_sensor
    from: closed
    platform: state
    to: open
  - entity_id: sensor.atrium_motion_sensor
    from: inactive
    platform: state
    to: active
  condition: []
  action:
  - data:
      entity_id: switch.atrium_lights
    entity_id: switch.atrium_lights
    service: switch.turn_on
- id: Atrium Lights Off
  alias: Atrium Lights Off
  trigger:
  - entity_id: sensor.front_door_sensor
    for:
      minutes: 5
    platform: state
    to: closed
  - entity_id: sensor.atrium_motion_sensor
    for:
      minutes: 5
    platform: state
    to: inactive
  condition: []
  action:
  - data:
      entity_id: switch.atrium_lights
    entity_id: switch.atrium_lights
    service: switch.turn_off
- id: Front Door Light On
  alias: Front Door Light On
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  action:
  - data:
      entity_id: switch.front_door_light_switch
    entity_id: switch.front_door_light_switch
    service: homeassistant.turn_on
- id: Front Door Light Off
  alias: Front Door Light Off
  trigger:
  - event: sunrise
    offset: 00:30:00
    platform: sun
  action:
  - data:
      entity_id: switch.front_door_light_switch
    entity_id: switch.front_door_light_switch
    service: homeassistant.turn_off
- id: Counter Light On
  alias: Counter Light On
  trigger:
  - at: '21:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: group.people
    state: home
  - after: '21:00:00'
    before: '23:00:00'
    condition: time
  action:
  - data:
      entity_id: light.counter_lights_level
    entity_id: light.counter_lights_level
    service: homeassistant.turn_on
- id: Counter Light Off
  alias: Counter Light Off
  trigger:
  - event: sunrise
    offset: -01:00:00
    platform: sun
  action:
  - data:
      entity_id: light.counter_lights_level
    entity_id: light.counter_lights_level
    service: homeassistant.turn_off
- id: Living and Kitchen On
  alias: Living and Kitchen On
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  - entity_id: sensor.garage_door_sensor
    platform: state
    to: open
  - above: 80
    entity_id: sensor.dark_sky_cloud_coverage
    platform: numeric_state
  condition:
  - condition: state
    entity_id: group.people
    state: home
  - after: '16:00:00'
    before: '23:00:00'
    condition: time
  action:
  - data:
      entity_id: scene.evening_lights
    entity_id: scene.evening_lights
    service: scene.turn_on
- id: Living and Kitchen Off
  alias: Living and Kitchen Off
  trigger:
  - entity_id: group.people
    platform: state
    to: not home
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: scene.evening_lights
    entity_id: scene.evening_lights
    service: scene.turn_off
  - data:
      entity_id: switch.master_bedroom_light_switch
    entity_id: switch.master_bedroom_light_switch
    service: homeassistant.turn_off
- id: Second Bedroom Light On
  alias: Second Bedroom Light On
  trigger:
  - entity_id: switch.second_bedroom_switch_switch
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: light.second_bedroom_light_level
    entity_id: light.second_bedroom_light_level
    service: light.turn_on
- id: Second Bedroom Light Off
  alias: Second Bedroom Light Off
  trigger:
  - entity_id: switch.second_bedroom_switch_switch
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: light.second_bedroom_light
    entity_id: light.second_bedroom_light_level
    service: light.turn_off
- id: Second Bedroom Switch On
  alias: Second Bedroom Switch On
  trigger:
  - entity_id: light.second_bedroom_light_level
    for:
      seconds: 5
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: switch.second_bedroom_switch_switch
    entity_id: switch.second_bedroom_switch_switch
    service: homeassistant.turn_on
- id: Second Bedroom Switch Off
  alias: Second Bedroom Switch Off
  trigger:
  - entity_id: light.second_bedroom_light_level
    for:
      seconds: 5
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: switch.second_bedroom_switch_switch
    entity_id: switch.second_bedroom_switch_switch
    service: homeassistant.turn_off
- id: Internet Failure
  alias: Internet Failure
  hide_entity: true
  trigger:
  - platform: state
    entity_id: sensor.internet_connection
    to: DOWN
    for:
      minutes: 5
  action:
  - service: notify.push
    data:
      message: Internet connection is DOWN
- id: Internet Restored
  alias: Internet Restored
  hide_entity: true
  trigger:
  - platform: state
    entity_id: sensor.internet_connection
    to: UP
  action:
  - service: notify.push
    data:
      message: Internet connection is restored
- id: Garage Door Left Open
  alias: Garage Door Left Open
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.garage_door_sensor
    to: open
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: group.people
    state: not home
  action:
    service: notify.push
    data:
      message: Garage Door Left Open
- id: On Backup Power
  alias: On Backup Power
  hide_entity: true
  trigger:
  - platform: state
    entity_id: sensor.ups_status_data
    to: OB
    for:
      minutes: 1
  action:
  - service: notify.push
    data:
      message: On Battery Power!
- id: On Normal Power
  alias: On Normal Power
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.ups_status_data
    to: LB
    from: OB
  action:
    service: notify.push
    data:
      message: Back on Normal Power
- id: Second Bathroom Door Open
  alias: Second Bathroom Door Open
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.second_bathroom_door_sensor
    to: open
    for:
      minutes: 1
  action:
    service: notify.push
    data:
      message: Second Bathroom Door Left Open
