homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Enables the frontend
frontend:
http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
# Checks for available updates
updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Track the sun
sun:
# Text to speech
tts:
  platform: google
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
emulated_hue:
  type: alexa
  host_ip: 192.168.1.104
sensor:
  - platform: darksky
    api_key: !secret dark_sky
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - wind_speed
      - cloud_cover
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - precip_intensity_max
media_player:
  - platform: samsungtv
    host: 192.168.1.3
camera:
    platform: generic
    still_image_url: http://192.168.1.201:80/Streaming/channels/1/picture
    name: front door
    username: !secret camera_user
    password: !secret camera_pass
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    home_interval: 10
    exclude:
     - 192.168.1.104
     - 192.168.1.106
     - 192.168.1.201
     - 192.168.1.219
