homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

# Enables the frontend
config:
frontend:
http:
  api_password: !secret api_password
updater:
discovery:
conversation:
history:
logbook:
sun:
tts:
  platform: google
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
emulated_hue:
  type: alexa
  host_ip: !secret media
notify:
  - name: push
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
mqtt:
  broker: !secret media
media_player:
  - platform: cast
    host: chromecast
  - platform: roku
  - platform: plex

digital_ocean:
  access_token: !secret do_token

group: !include groups.yaml
scene: !include scenes.yaml
automation: !include_dir_merge_list automations/
camera: !include cameras.yaml
device_tracker: !include device_tracker.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
