  #- platform: nmap_tracker
  #  hosts: 192.168.1.1/24
  #  home_interval: 10
  #  exclude:
  #   - !secret media
  #   - !secret synology
  #   - !secret front_camera
  #   - !secret garage_camera

- platform: unifi
  host: !secret alpha
  username: !secret unifi_user
  password: !secret unifi_password
  track_new_devices: false
  interval_seconds: 10
  verify_ssl: False
  exclude:
   - !secret alpha
   - !secret media
   - !secret synology
   - !secret front_camera
   - !secret garage_camera

