- platform: mqtt_json
  name: "SN1 LED"
  state_topic: "mr/sensornode1"
  command_topic: "mr/sensornode1/set"
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0
- platform: flux_led
  automatic_add: true
  devices:
    192.168.1.236:
      name: luca_bedroom_underlights
