- platform: mqtt
  name: "Master Bathroom Light"
  state_topic: "smartthings/Master Bathroom Light/switch"
  command_topic: "smartthings/Master Bathroom Light/switch"
  brightness_state_topic: "smartthings/Master Bathroom Light/level" 
  brightness_command_topic: "smartthings/Master Bathroom Light/level" 
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Counter Lights"
  state_topic: "smartthings/Counter Lights/switch"
  command_topic: "smartthings/Counter Lights/switch"
  brightness_state_topic: "smartthings/Counter Lights/level"
  brightness_command_topic: "smartthings/Counter Lights/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Living Room Light"
  state_topic: "smartthings/Living Room Light/switch"
  command_topic: "smartthings/Living Room Light/switch"
  brightness_state_topic: "smartthings/Living Room Light/level"
  brightness_command_topic: "smartthings/Living Room Light/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Second Bedroom Light"
  state_topic: "smartthings/Second Bedroom Light/switch"
  command_topic: "smartthings/Second Bedroom Light/switch"
  brightness_state_topic: "smartthings/Second Bedroom Light/level"
  brightness_command_topic: "smartthings/Second Bedroom Light/level"
  payload_on: "on"
  payload_off: "off"
  retain: true


