- platform: command_line
  name: Internet Connection
  command: ping -q -c 1 -W 1 google.com > /dev/null 2>&1 && echo UP || echo DOWN
  scan_interval: 120

- platform: darksky
  api_key: !secret dark_sky
  monitored_conditions:
    - summary
    - precip_type
    - precip_probability
    - temperature
    - cloud_cover

# - platform: fastdotcom

- platform: plex

- platform: cpuspeed

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use

- platform: time_date
  display_options:
    - 'time'

- platform: transmission
  host: !secret synology
  port: 9091
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

- platform: nut
  name: UPS
  host: !secret synology
  username: !secret ups_username
  password: !secret ups_password
  resources:
    - ups.load
    - ups.status
    - ups.realpower.nominal
    - input.voltage
    - battery.runtime

#- platform: octoprint
#  name: OctoPrint
#  monitored_conditions:
#    - Current State
#    - Job Percentage

- platform: template
  sensors:
    front_door_sensor:
      value_template: >
        {% if is_state('sensor.front_door_sensor_alarm_level', '255') %}
            open
        {% else %}
            closed
        {% endif %}
      friendly_name: Front Door Status
    atrium_motion_sensor:
      value_template: >
        {% if is_state('sensor.atrium_motion_sensor_alarm_level', '255') %}
            active
        {% else %}
            inactive
        {% endif %}
      friendly_name: Atrium Motion Status
    garage_door_sensor:
      value_template: >
        {% if is_state('sensor.garage_door_sensor_alarm_level', '255') %}
            open
        {% else %}
            closed
        {% endif %}
      friendly_name: Right Garage Door Status
    left_garage_door_sensor:
      value_template: >
        {% if is_state('sensor.left_garage_door_sensor_alarm_level', '255') %}
            open
        {% else %}
            closed
        {% endif %}
      friendly_name: Left Garage Door Status
    second_bathroom_door_sensor:
      value_template: >
        {% if is_state('sensor.second_bathroom_exterior_door_alarm_level', '255') %}
            open
        {% else %}
            closed
        {% endif %}
      friendly_name: Second Bathroom Door Status
    back_sliding_door_sensor:
      value_template: >
        {% if is_state('sensor.back_sliding_door_sensor_alarm_level', '255') %}
            open
        {% else %}
            closed
        {% endif %}
      friendly_name: Back Sliding Door Status


- platform: mqtt
  state_topic: "mr/multisensor1"
  name: "SN1 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "mr/multisensor1"
  name: "SN1 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "mr/multisensor1"
  name: "SN1 PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "mr/multisensor1"
  name: "SN1 Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "mr/multisensor2"
  name: "SN2 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "mr/multisensor2"
  name: "SN2 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "mr/multisensor2"
  name: "SN2 PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "mr/multisensor2"
  name: "SN2 Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "mr/multisensor3"
  name: "SN3 Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "mr/multisensor3"
  name: "SN3 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "mr/multisensor3"
  name: "SN3 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "mr/multisensor3"
  name: "SN3 PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "mr/multisensor4"
  name: "SN4 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "mr/multisensor4"
  name: "SN4 PIR"
  value_template: '{{ value_json.motion }}'


- platform: mqtt
  state_topic: "mr/multisensor5"
  name: "SN5 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "mr/multisensor5"
  name: "SN5 PIR"
  value_template: '{{ value_json.motion }}'


