- platform: command_line
  name: Internet Connection
  command: ping -q -c 1 -W 1 google.com > /dev/null 2>&1 && echo UP || echo DOWN
  scan_interval: 120

- platform: darksky
  api_key: !secret dark_sky
  monitored_conditions:
    - summary
    - precip_type
    - precip_probability
    - temperature
    - cloud_cover

# - platform: fastdotcom

- platform: plex

- platform: cpuspeed

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use

- platform: time_date
  display_options:
    - 'time'

- platform: transmission
  host: !secret synology
  port: 9091
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

- platform: nut
  name: UPS
  host: !secret synology
  username: !secret ups_username
  password: !secret ups_password
  resources:
    - ups.load
    - ups.status
    - ups.realpower.nominal
    - input.voltage
    - battery.runtime

#- platform: octoprint
#  name: OctoPrint
#  monitored_conditions:
#    - Current State
#    - Job Percentage

- platform: mqtt
  state_topic: "mr/sensornode1"
  name: "SN1 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "mr/sensornode1"
  name: "SN1 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "mr/sensornode1"
  name: "SN1 PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "mr/sensornode1"
  name: "SN1 Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "mr/multisensor2"
  name: "SN2 Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "mr/multisensor2"
  name: "SN2 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "mr/multisensor2"
  name: "SN2 PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "mr/multisensor2"
  name: "SN2 Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'
