- platform: command_line
  name: Internet Connection
  command: ping -q -c 1 -W 1 google.com > /dev/null 2>&1 && echo UP || echo DOWN
  scan_interval: 120

- platform: darksky
  api_key: !secret dark_sky
  monitored_conditions:
    - summary
    - precip_type
    - precip_probability
    - temperature
    - cloud_cover

# - platform: fastdotcom

- platform: plex

- platform: cpuspeed

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use

- platform: time_date
  display_options:
    - 'time'
 
- platform: transmission
  host: !secret synology
  port: 9091
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

- platform: mqtt
  state_topic: smartthings/Front Door Sensor/contact
  name: "Front Door Sensor"
  sensor_class: opening
  retain: true

- platform: mqtt
  state_topic: smartthings/Atrium Motion sensor/motion
  name: "Atrium Motion Sensor"
  sensor_class: motion
  retain: true

- platform: mqtt
  state_topic: smartthings/Garage Door/contact
  name: "Garage Door"
  sensor_class: opening
  retain: true

- platform: nut
  name: UPS
  host: !secret synology
  username: !secret ups_username
  password: !secret ups_password
  resources:
    - ups.load
    - ups.status
    - ups.realpower.nominal
    - input.voltage
    - battery.runtime

- platform: octoprint
  name: OctoPrint
  monitored_conditions:
    - Current State
    - Job Percentage

