- platform: command_line
  name: Internet Connection
  sensor_class: connectivity
  command: ping -q -c 1 -W 1 google.com > /dev/null 2>&1 && echo UP || echo DOWN
  scan_interval: 120

- platform: darksky
  api_key: !secret dark_sky
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - wind_speed
    - cloud_cover
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min

# - platform: fastdotcom
 
- platform: transmission
  host: !secret media
  port: 9091
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

- platform: mqtt
  state_topic: smartthings/Front Door Sensor/contact
  name: "Front Door Sensor"
  sensor_class: opening
  retain: true

- platform: mqtt
  state_topic: smartthings/Atrium Motion sensor/motion
  name: "Atrium Motion Sensor"
  sensor_class: motion
  retain: true

