- platform: mqtt
  name: "Hall Light"
  state_topic: "smartthings/Hall Light/switch"
  command_topic: "smartthings/Hall Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

#- platform: mqtt
#  name: "Atrium Lights"
#  state_topic: "smartthings/Atrium Lights/switch"
#  command_topic: "smartthings/Atrium Lights/switch"
#  payload_on: "on"
#  payload_off: "off"
#  retain: true

- platform: command_line
  switches:
    atrium_lights:
      command_on: "/usr/bin/curl -X GET http://192.168.1.2/led/1"
      command_off: "/usr/bin/curl -X GET http://192.168.1.2/led/0"
      command_state: "/usr/bin/curl -X GET http://192.168.1.2/led"
      value_template: '{{ value == "status: 1" }}'
      friendly_name: Atrium Lights

- platform: mqtt
  name: "Kitchen Light"
  state_topic: "smartthings/Kitchen Light/switch"
  command_topic: "smartthings/Kitchen Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Master Bedroom Light"
  state_topic: "smartthings/Master Bedroom Light/switch"
  command_topic: "smartthings/Master Bedroom Light/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Second Bedroom Switch"
  state_topic: "smartthings/Second Bedroom Switch/switch"
  command_topic: "smartthings/Second Bedroom Switch/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Front Door"
  state_topic: "smartthings/Front Door/switch"
  command_topic: "smartthings/Front Door/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: transmission
  host: !secret synology

- platform: broadlink
  friendly_name: "Second Bedroom AC"
  host: !secret ac_remote
  mac: !secret ac_remote_mac
  timeout: 30
  switches:
    heat_on_68_auto: 
      friendly_name: 'Heat On at 68 Auto'
      command_on: 'JgBQAg0ODg8NEA0ODg8NAANEcToNLQwPEA0NDxAqDwwQDQ8NEA0PKg8NDyoQKRANDyoQKRApECoPKg8NDw0PKhANDw0QDA4PDw0ODw4ODw0PDg0ODiwNDw4rDg8ODwwPDisOLA0PDg8MEA0PDisODw0PDQ8ODw0QDA8ODw0PDg4NEA0PDisOLA0sDQ8NDw0sDisOLA0ABHxzOQ4rDw0PDg4ODyoQDBANEAwQDBAqDw0QKRAqDw0PKg8rDisPKg8qDw0QDBAqDw0QDBAMEA0QDQ8MEA0QDQ4NEA0QDBAqDwwQDRAMEA0PKg8NEA0PDRApECkQKg8qEAsQKhAMECkQDRANDyoPKg8NDw0QDQ8qDw0QDBANEAwPKhAMEAAEenQ3ECoPDRANDw0PKg8NEA0QDA8NECkQDRApECkQDBApECkQKg8qECkQDQ8NECkQDQ8NDw0QDRAMDw0QDQ8NDw0QDQ8NEAwQDQ8NEAwPDRANEA0OKw8MEA0QKRApECoPDRAMECkQDQ8NEA0PKg8qDw0QDQ8NEAwPDRANEA0ODRANEAwPDRANDw0QDBANDyoQDBAqDw0PDRAMEA0QDA8NEA0QDQ4NEA0QDA8NEA0PDRAMEA0PDRApECoPDQ8NEAwQDRAMDw0QDRAMDw0QDQ8qECkQDQ8MEA0QDQ8MEA0QDBANDw0PDRANEAwPDRANEAwPDRANDyoQDQ8MEA0PDRAMECkQKRANEA0PDQ8NEA0PDRAMDyoQDQ8NEA0PDBANEA0PDBANECkQKRANEAwPDRANDyoQKRAADQUQKg8NEA0PDQ=='
      command_off: 'JgBUAgQAB+oOEAwQDBANEA0ODAADRHE7DS0NDw0PDRAMLA4QDA8NEAwQDC0NDwwsDi0NDw0sDSwOKw4rDSwNEQ0PDC0MEA0QDQ8PDQ0QDBANEAwQDBANEA0sDQ8NKw4PDRANEAstDSwNEA0PDRAMDw4rDg8NEA8MDRANEA0PDBANEA0PDQ8MEA0tDSsOKw4QDQ8MLQwtDS0MAAR7czkOKw4QDQ8NEAwsDRANDw0QDQ8MLQ0PDSwOKw4PDSwMLQ4rDisOKw4QDA8OLA0PDRANDw0PDRANDg8ODRANDwwQDBANLQ0PDQ8MEQwQDSwPDgwQDSsOLA0QDCwODw0sDQ8NEA0rDg8NDw0sDRANEAwQDBANDw4sDSsOKw4rDhANKw4ABHtzOQ4sDQ8NDw0QDSsNEQwPDg8NEAwsDRANKw4rDg8OKw4rDisOKw4sDRANDw0rDg8ODw8ODA8NEA0QDQ4NEA0PDg8MEA0PDRANDw0PDRANDg4PDBENDwwQDSsOEA0PDSwNDw0QDQ8NEAwsDBENKw4QDQ8NDw0PDRANDw0PDRANDw0PDRANDwwQDRANDw8qDg8MLA4PDQ8QDQ0PDQ8NEA0PDBANEA0PDg4NEAwQDQ8NEA0PDRAMLA0sDRANDw4PDBANDw0QDQ8MEA0QDQ8MLQ0sDQ8ODw0QDQ4NEA0PDg8MEA0PDRANDw0PDRANDw0PDBENDw0rDg8NEA0PDQ8NEA0rDisOEA0PDBAMEA4PDQ8NDw4rDg8MEQwPDg8NEAwPDRANDw0tDQ4NEA0rDhANDw0sDyoNAA0FDQ8NEA=='
    ac_on_73_auto:
      friendly_name: 'AC On at 73 Auto'
      command_on: 'JgBQAg0ODhANDw0PDRAMAANEcjkNLA0PDRANEAwsDg8MEA0QDQ8MLQwQDisOKw0QDSwNLA4rDisOLA4ODRAMLA4PDRANDg0QDg8MEQsQDRANDw0ODisPDwwsDhAMEA0ODSwOKw8ODRANDg4QDCwNEA0PDQ8ODw0QDA8NEA0PDQ8NEA0PDisNLA4rDw4MEQwsDSwNLA4ABHxxOg4sDQ8NEAwQDSwNEAwQDQ8NDw0sDg8NLA4rDhALLQwtDC0NLA4sDBAODg0sDRAODg0QDQ8NEAwQDQ8ODwsQDQ8PDwwsDQ8NEA0QDBELLQ0PDg4NLA4QDCwOKw4ODisODw0QDSsPDwsQDSwNEA0QDA8NEA0QDA8ODw0QDBAMLQwtDAAEfXI6DSwMEA0QDRAMLA4PDQ4OEAwRCy0NDw0sDisODg4sDisNLA4rDSwODwwQDisODg4QDQ8MDw4PDQ8ODwwQDQ8ODwwQDRAMEAsRDg8MEAwPDhANKw4QDA8NLA4rDSwNEA4ODRAMLQwtDC0NDw0sDhAMDw4PDBENDwwRCxANDw0RCw8PDg4PDg4MEA0PDysODwstDQ8NEQwPDg8MEA4PDBELEA0QDBANDw0QDBANDg0RDA8PDgwtDC0NEAwQDg8MDw4PDQ8OEAsQDBENEAwsDSwODg4ODRANDw0PDRANEAwQDBANDw0QDA8OEAwRCxANDw4PDisNDw0PDRAODQ4QDSsOKw0QDQ8NEAwQDQ8ODg0QDisODg4QChIMDw4QDQ4NEA0PDRAMDw4PDg8LEA0PDysNLA0ADQUNLAwQDRANEA=='
      command_off: 'JgBQAg0ODg8NEAwPDg8NAANDcToOLA0PDRANDg8rDQ8NEA0PDQ8NLA4PDSwNLA4PDisNLA4rDisOLA0ODg8NLA0QDQ8NDw0QDQ8ODg0QDQ8NDw0PDiwNDw4rDg8MEA4ODisOLA0PDg4NDw8ODSwODwwQDQ8NEA0ODg8NEA0PDQ8NDw4PDSwNLA4sDA8ODw0sDisOKw4ABHxxOg4sDQ8ODg0PDiwNDw4PDBANDw0sDw4NLA0sDg4NLA4rDyoOLA0sDQ8ODw0sDg4NEA0PDRAMDw4PDRANDg4PDg4ODw0sDg4NEA0PDQ8NLA0QDSwNLA0QDSwNLA0PDSwNDw4PDSwNEAwPDiwNDw4PDQ8NLA0PDg8NDw0PDg8NLA0sDgAEfHE6DSwODwwQDQ8OKw4PDQ8NDw4PDSwNEAwtDC0NDw0sDSwNLA4rDiwNDw4PDSwODg0PDg8NDw0PDg8NDw0PDRANDw4ODQ8ODw0QDA8ODw0QDQ4ODw0PDg8MLQ4rDS0MDw4PDQ8OLA0sDSwNDw0sDQ8ODw0PDQ8ODw0QDQ4ODw0PDg4NEA0PDg8MEA0PDSwODw0sDQ8NDw4PDQ8NDw4PDQ8NDw4PDQ8ODg0QDQ8ODwwPDg8NEA0sDSwNDw0PDw4NDw0PDg8NDw0PDRANDw4rDiwNDg4PDQ8ODw0PDQ8ODw0PDQ8ODw0PDQ8NEA0PDQ8NEA0PDisODg4PDQ8ODwwQDSwNLA0QDQ8NDw0PDg8NEAwPDisODw0QDA8ODw0PDg4ODw0PDiwNLA0sDSwOKw4rDg8NLA4ADQUNLA4PDBANDw=='
    ac_on_76_auto:
      friendly_name: 'AC On at 76 Auto'
      command_on: 'JgBQAg0PDQ8ODw0ODg8OAANDcToOLAwPDg8NDw4sDQ4ODw0QDQ8NLA0PDisOKw4PDisOKw4sDSwNLA0PDg4OKw4PDRANDg4PDQ8ODw0PDQ8ODw0PDSwNDw4sDQ8ODwwPDiwNLA0PDg8ODg0PDisODw4PDA8ODw0QDA8ODw0PDg4ODw0PDisOLA0sDQ8NDw4rDiwNLA0ABHxyOg0sDg8NDw4ODSwODw0PDg4NEA0sDQ8OKw4sDQ8NLQ0sDC0MLQ0sDQ8NEA0sDQ8ODg4PDQ8ODwwPDg8ODw0ODg8NEA0sDQ4ODw4PDQ8NLA0PDisODw0PDiwNLA0PDQ8OKw4rDg8OKw4rDg8NLA0PDRANDw4rDg4NLA4rDg8NEA0ODgAEfHE6DiwNDw4PDQ8NLQwPDg8NDw4ODisODw0sDisODw0sDisOKw4sDSwNDw0PDisODw0PDQ8ODw0PDg4ODw0PDg8MDw4PDg8NDg4PDRANDw0PDQ8OLA0PDg4NLA4rDisODw4PDSwNDg4PDg8NLA0sDg8MDw4PDRANDg4PDQ8ODw0PDQ8ODw0PDQ8ODw0ODiwNDw4rDg8ODwwPDg8NEA0ODg8NDw4PDQ8NDw4PDQ8NDw4PDQ4ODw4rDisODw4PDA8ODw0PDg4ODw0PDg8NDw0sDSwODw0PDg4NDw4PDg8MDw4PDRAMDw4PDQ8ODg4PDQ8ODw0PDSwNDw4PDg4NDw4PDSwOKw4PDBANDw4PDA8ODw4PDSwNDg4PDg8NDw0PDRANDw4ODSwOKw4PDQ8ODw0PDSwNLA4ADQUOLA0PDg8NDw=='
      command_off: 'JgBQAg4ODg8NDw0PDRANAANCcjoOKw4PDQ8ODw0sDQ8NDw4PDQ8NLA0PDiwNLA0PDiwNLA0sDisOKw4ODg8NLA0PDg8NDw0PDg8NDw0PDg8NDw0PDisODw0sDg8NDg4PDSwOKw4PDQ8NDw4PDSwODwwPDg8NDw4ODg8NDw4PDQ8NDw4PDSwOKw4rDg4ODw0sDSwOKw4ABHxxOg4sDQ8ODg0PDiwNDw4PDA8ODw4rDg8NLA4rDg4NLA4rDisOLA0sDQ8ODw4rDg8MDw4PDg8MDw4PDg8NDg4PDQ8ODw0sDQ8NEA0PDg4NLA4PDSwNLA0QDSwNLA0PDQ8OKw4sDQ8OKw4sDQ8NLA0PDg8NDw4ODSwOKw4rDg8ODw0PDQAEe3M6DS0MDw4PDQ8OLA0ODg8NDw4ODisODw0sDisODw0sDisOKw4sDSwNDw0PDisODw0QDQ4ODw0PDg8NDw0PDg8NDw0PDg8NDw0PDg8NDw0PDRANDw4ODQ8OLA0sDSwODw0PDSwODg4PDQ8OKw4sDQ4ODw0PDg8NDw0PDg8NDw0PDg8NDw0PDg8NDw0PDisODw0sDRANDg4PDQ8ODw0PDQ8ODw0PDQ8ODw0ODg8ODw0PDQ8NEA0sDSwNEA0ODg8NDw4PDQ8NDw4PDQ8NDw4rDiwNDw4ODQ8ODw4PDA8ODw0PDg4ODw0PDg8NDw0PDg8NDw0PDisODw0PDQ8ODw0PDS0MLQwPDg8ODw0ODg8NEA0PDSwNDw4PDQ8ODg0PDg8ODg0PDg8NLA4PDA8ODw4PDSwNLA4ADQUNLQwPDg8NDw==' 
    auto_75_on:
      friendly_name: 'Full Auto at 75'
      command_on: 'JgBQAg4ODg8NDg4PDRANAANDcToOKw4PDRANDg4rDg8NEA0PDQ8QKQ0QDSwNLBANDSwNLA0sDisOLA0ODg8NLA0QDQ4ODw0QDQ8NDw0PDg8NDw0PDisODw0sDg8MEA0PDisOKw4PDQ8NDw4PDSwODwwPDg8NEAwPDg8NDw4ODg8NDw4PDC0NLA4sDQ4ODw0sDSwOKw4ABHxzOBAqDw0QDA8ODyoQDBAMDw4PDRApEA0PKg8qDw0PKhEoESkPKhApDw4QDBApEAwPDg8NEA0ODg8NEA0PDBANDw4PDBApEA0PDg8NDw0PKhANDyoQKQ8qECkQDQ8qECoQKQ8MECkQDQ8qECkQDQ8ODg0QKg8NDyoQKg8qDw0QKRAMDwAEe3E6DisODw4PDQ4OLA0PDg8NDw0PDSwODg4sDSwODw0sDSwOKw4sDSwNDg4PDSwODw0PDQ8NEA0PDQ8NEA0PDg4NEA0PDRAMDg8PDRANDg4PDQ8OLA0NDw8NLA0QDQ8ODg0QDQ8ODg0QDQ8NLA4rDg8MEA0PDg4ODw0PDg8NDw0PDRANDw4ODRANDw0PDSwNEA0sDQ8ODw0PDQ8ODw0PDgwQDw0PDQ8NEA0ODw4NEA0PDQ8NDw8rDSwNDg8PDBANDw4PDQ8NDw0ODw8NDw0sDisODw0QDQ4ODw0QDQ8MEA0PDg8MEA0PDg8NDw0PDRANDg4PDSwOCxEPDg4NEA0PDisOLA0PDQ8NEA0PDQ8NDw4PDSwODg0PDg4OEAwPDg8NEA0ODg8NLA0QDQ8NLA0PDRANLA0ADQUOKw4PDg8NDg=='
      command_off: 'JgBQAhAMDw0QDQ8NDw0PAANCczgRKQ8MEA0PDRAqDw0PDQ8ODw0QKRAMDyoQKRANDyoQKRAqDyoNLA8NEAwQKRANDw4PDQ8NDw0QDQ8NDw0QDQ8ODisODRAqDw0QDQ8MECoPKg8NEA0PDQ8NECoPDQ8ODg0QDQ0QDwwQDQ8NEA0NDw8NECoNLA8qDQ8ODg4rDiwNLA0ABHxyOg0sDRANDxAMDSwODw0PDg8MEA0sDQ8OLA0sDQ8QKg0sDSwNLA4rDg4NEA8qDQ8ODwwQDQ8ODw0PDQ8PDg0OEA0NEA0sDQ8NDw8ODQ8OKw4ODisOKw4sDSwNDw4sDSwNLA0QDSwNDw0tDC0NDhANDRANLA0PDSwNLA0sDRANLA0PDgAEe3I6DiwNDg4PDRANLA0PDQ8ODw0PDisODg4rDiwNDw4rDiwNKg8sDSwNEA0PDSwODg4PDQ8NDw0QDQ8ODg0PDg8ODwwPDg8NEA0ODg8NDw4PDQ8NDw4PDBANLA0PDg8NDw0PDg8NDw0PDg8NLA0sDg8NDg4PDRANDw0PDQ8ODw4ODQ8ODw0PDQ8ODw0PDS0MDw4sDQ8ODw0ODg8NEA0PDQ8NDw4PDQ8NDw4PDQ8NDw4PDQ8NDw4rDisODw4PDQ4ODw0QDQ8NDw0PDg8NDw0sDSwODw0PDg4NEA0PDg8MDw4PDRANDg4PDRANDw0PDQ8ODw0PDSwNDw4PDRAMDw4PDSwOKw4PDBANDw4PDQ8NDw4PDSwNDw0PDg8NDw4ODRANDw4PDC0NDw0PDg8MLQ0PDQ8OLA0ADQUOLA0ODg8NEA=='
    heat_69_quiet:
      friendly_name: 'Quiet Heat at 69'
      command_on: 'JgBQAg4ODQ8ODw0PDQ8OAANCcjoNLA0QDQ8ODwwtDQ8NDw4PDQ4OLA0PDisOLA0PDisOLA0sDSwNLA4PDA8OLA0PDg8MDw4PDg8NDg4PDRANDw0PDSwODw0sDQ8ODg4PDSwNKw8PDQ8NDw0QDSwNDw4ODg8NDw4ODQ8ODw4PDA8ODw0QDSwNLA0sDg4NDw4sDSwNLA0ABHxyOg4rDg8NDw0PDisODw0PDQ8ODw0sDRANLA0sDQ8NLA0sDSwOKw4rDg8ODw0sDQ8NDw4PDQ8ODg4PDQ8ODwwQDQ8ODwwtDBANDw4PDQ4OLA0PDisOLA0sDQ8ODw0PDSwNLA4PDSwNDw4ODisOKw4PDg8NLA0PDS0MLQwPDg8OKw4PDAAEfXI6DSwNDw0PDg8OKw4ODQ8ODw4PDC0MEA0sDSwNEA0sDSwNLA4rDisODw4ODSwNDw4PDg4NDw4PDRAMDw4PDQ8ODg4PDQ8ODwwQDQ8ODw0PDQ8OKw4PDQ8NLQwPDg8NLA4PDC0MEA8NDisODw0sDg4PDQ4PDg8MDw4PDQ8ODhANDQ8QDQ0PDQ8ODwwtDSwNDw0sDg8NDxAMDw4NDxANDA8ODw4PDQ4ODw0QDQ8NDw0PDg8NDw0sDSwODw0PEAwNEA0PDg8MDw4PDg8NDhApDiwNDw4PDQ8NDw4PDQ8PDQ4PDQ8ODg0PEA0ODwwPDg8NEA8MDisODw4PDQ8NDw0QDSwNLA4ODg4QDQ8NDg4ODw8NDisODw0PDw0ODw0PDQ8ODw0PDS0MLQwPDiwNLA0PDiwNLA0ADQUNLA0PDQ8ODw=='
      command_off: 'JgBQAg8NDw0QDQ8NDw0QAANBdDgOKw4NEA0PDg4rDg4PDRANDwwQKg8NECkQKg8NECkQKg8qDyoPKg8ODg0QKRANEA0PDBANDw4PDQ8NDw0QDQ8NDyoPDg8qDw0QDA8ODyoPKg8ODw0PDQ8NECoPDRAMDw4PDQ8ODg0QDQ8ODg0QDQ8NECoPKg8qDw0PDRApECoPKg8ABHp0OA8qDw4PDQ8NDyoQDQ8NEAwPDg8qDw0QKg8qDwwQKg8qDyoPKhApEA0PDg8qDw0PDQ8ODw0PDQ8ODw0PDg4NEA0PDg8qDwwQDQ8ODw0PKg8NDw4PDQ8NDyoQDQ8NECoPKg8MECoPDRANDyoPKhANDg0QDQ8qECkQKg8NEAwPKg8ODwAEenQ4DyoPDg8MEA0NLA8ODw0PDQ8NECoPDQ8qECoPDBApECoPKg8qDyoQDQ8NECoPDQ8NDw0ODw8NDw0QDQ8NDw0PDg8NDw0PDg8NEAwPDg8NDw4ODRANDw4PKg8NDw0PKhANDyoPDQ8NECoPDQ8qEA0ODg8NDw4PDQ8NDw4PDQ8NDw4PDQ8NDw0QDQ8qDyoQDQ4rDw0PDRANDg4PDRANDw0PDRANDw0PDQ8ODw0ODg8ODw0ODw4rDisPDQ8NEA0ODg8NEA0PDQ8NDw4PDQ8rDisODRANDw4PDA8ODw0QDQ4ODw0QDQ4ODQ8QDQ8NDw0PDg8NDysODQ8ODw0ODg8ODyoPKg8ODw0PDQ0QDw0PDQ8NECoPDQ8NDw0ODw8ODg0QDQ8ODwwPKhANDyoPKhANDyoPKhAADQUPKg8ODwwQDQ=='
