- alias: 'Atrium Lights On'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_sensor_sensor_11_0
      state: 'open'
    - platform: state
      entity_id: binary_sensor.atrium_motion_sensor_sensor_12_0
      state: 'active'
  condition:
     condition: or
     conditions:
       - condition: sun
         after: sunset
         after_offset: '-00:45:00'
       - condition: sun
         before: sunrise
         before_offset: '00:45:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.atrium_lights
- alias: 'Atrium Lights Off'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_sensor_sensor_11_0
      state: 'closed'
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.atrium_motion_sensor_sensor_12_0
      state: 'inactive'
      for:
        minutes: 5
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-00:45:00'
      - condition: sun
        before: sunrise
        before_offset: '00:51:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.atrium_lights
