- alias: 'Front Door Light On'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.front_door

- alias: 'Front Door Light Off'
  trigger:
    platform: sun
    event: sunrise
    offset: '00:30:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.front_door

- alias: 'Counter Light On'
  trigger:
    platform: time
    after: '21:00:00' 
  condition:
    - condition: state
      entity_id: group.people
      state: 'home'
    - condition: time 
      after: '21:00:00'
      before: '23:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.counter_lights

- alias: 'Counter Light Off'
  trigger:
    platform: sun
    event: sunrise
    offset: '-01:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.counter_lights 

- alias: 'Living and Kitchen On'
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
    - platform: state
      entity_id: sensor.garage_door
      state: 'open'
    - platform: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      above: 80
  condition:
    - condition: state
      entity_id: group.people
      state: 'home'
    - condition: time 
      after: '16:00:00'
      before: '23:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.evening_lights

- alias: 'Living and Kitchen Off'
  trigger:
    - platform: state
      entity_id: group.people
      state: 'not home'
  condition:
    condition: sun
    after: sunset
  action:
    - service: scene.turn_off
      entity_id: scene.evening_lights
    - service: homeassistant.turn_off
      entity_id: switch.master_bedroom_light

- alias: 'Second Bedroom Light On'
  trigger:
    platform: state
    entity_id: switch.second_bedroom_switch
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.second_bedroom_light

- alias: 'Second Bedroom Light Off'
  trigger:
    platform: state
    entity_id: switch.second_bedroom_switch
    from: 'on'
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: switch.second_bedroom_light

- alias: 'Second Bedroom Switch On'
  trigger:
    platform: state
    entity_id: switch.second_bedroom_light
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.second_bedroom_switch

- alias: 'Second Bedroom Switch Off'
  trigger:
    platform: state
    entity_id: switch.second_bedroom_light
    from: 'on'
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: switch.second_bedroom_switch
