- alias: 'Front Door Light On'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.front_door

- alias: 'Front Door Light Off'
  trigger:
    platform: sun
    event: sunrise
    offset: '00:30:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.front_door

- alias: 'Counter Light On'
  trigger:
    platform: time
    after: '21:00:00' 
  condition:
    - condition: state
      entity_id: group.people
      state: 'home'
    - condition: time 
      after: '21:00:00'
      before: '23:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.counter_lights

- alias: 'Counter Light Off'
  trigger:
    platform: sun
    event: sunrise
    offset: '-01:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.counter_lights 

- alias: 'Living and Kitchen On'
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    - condition: state
      entity_id: group.people
      state: 'home'
    - condition: time 
      after: '16:00:00'
      before: '23:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.evening_lights
