- alias: 'Internet Failure'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.internet_connection
      to: 'DOWN'
      for:
        minutes: 5
  action: 
    - service: notify.push
      data:
        message: "Internet connection is DOWN"

- alias: 'Internet Restored'
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.internet_connection
      to: 'UP'
  action: 
    - service: notify.push
      data:
        message: "Internet connection is restored"

- alias: 'Garage Door Left Open'
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.garage_door
    to: 'open'
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: group.people
    state: 'not home'
  action:
    service: notify.push
    data:
      message: "Garage Door Left Open"

- alias: 'On Backup Power'
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.ups_status_data
      to: 'OB'
      for:
        minutes: 1
  action:
    - service: notify.push
      data: 
        message: "On Battery Power!"

- alias: 'On Normal Power'
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.ups_status_data
    to: 'LB'
    from: 'OB'
  action:
    service: notify.push
    data:
      message: "Back on Normal Power"
